# Generated by Django 4.2.23 on 2025-08-09 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("descricao", models.TextField()),
                ("local", models.CharField(max_length=255)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
                ("quantidade_vagas", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
