# Generated by Django 4.2.23 on 2025-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Igreja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("endereco", models.CharField(max_length=255)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("pastor_responsavel", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Igreja",
                "verbose_name_plural": "Igrejas",
            },
        ),
    ]
