# Generated by Django 4.2.23 on 2025-08-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("igrejas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("endereco", models.TextField()),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("visitante", "Visitante"),
                            ("afastado", "Afastado"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                (
                    "igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="igrejas.igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro",
                "verbose_name_plural": "Membros",
            },
        ),
    ]
