# Generated by Django 4.2.23 on 2025-08-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                ("pago", models.BooleanField(default=False)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eventos.evento"
                    ),
                ),
            ],
        ),
    ]
