# Generated by Django 4.2.23 on 2025-08-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membros", "0001_initial"),
        ("inscricoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="membro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="membros.membro"
            ),
        ),
    ]
